<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>proxygen: gtest_catch_exceptions_test.CatchCxxExceptionsTest Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">proxygen
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.html"><span>Related&#160;Pages</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
      <li><a href="examples.html"><span>Examples</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.html"><span>Class&#160;List</span></a></li>
      <li><a href="hierarchy.html"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html','');});
</script>
<div id="doc-content">
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest-members.html">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">gtest_catch_exceptions_test.CatchCxxExceptionsTest Class Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="dynheader">
Inheritance diagram for gtest_catch_exceptions_test.CatchCxxExceptionsTest:</div>
<div class="dyncontent">
 <div class="center">
  <img src="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.png" usemap="#gtest_5Fcatch_5Fexceptions_5Ftest.CatchCxxExceptionsTest_map" alt=""/>
  <map id="gtest_5Fcatch_5Fexceptions_5Ftest.CatchCxxExceptionsTest_map" name="gtest_catch_exceptions_test.CatchCxxExceptionsTest_map">
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a7d02a890df0e3990aa107288c21f7dc7"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">testCatchesCxxExceptionsInFixtureConstructor</a> (self)</td></tr>
<tr class="separator:a7d02a890df0e3990aa107288c21f7dc7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3fe17da71b72c1693fa358f71c6b31be"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">testCatchesCxxExceptionsInFixtureDestructor</a> (self)</td></tr>
<tr class="separator:a3fe17da71b72c1693fa358f71c6b31be"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8e791760b553d92490005deea0812f44"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">testCatchesCxxExceptionsInSetUpTestCase</a> (self)</td></tr>
<tr class="separator:a8e791760b553d92490005deea0812f44"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a56c906c34e689ee016ab1bf14fe5220c"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">testCatchesCxxExceptionsInTearDownTestCase</a> (self)</td></tr>
<tr class="separator:a56c906c34e689ee016ab1bf14fe5220c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6451307941e063bcc3927992c1f2df54"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">testCatchesCxxExceptionsInSetUp</a> (self)</td></tr>
<tr class="separator:a6451307941e063bcc3927992c1f2df54"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a40ba50bf018753b7b21ed93ed60e4e1c"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">testCatchesCxxExceptionsInTearDown</a> (self)</td></tr>
<tr class="separator:a40ba50bf018753b7b21ed93ed60e4e1c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac73b336590a3d1c242124e9ea5464a42"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">testCatchesCxxExceptionsInTestBody</a> (self)</td></tr>
<tr class="separator:ac73b336590a3d1c242124e9ea5464a42"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a922cb0b598034924c19e6695cc9f7513"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">testCatchesNonStdCxxExceptions</a> (self)</td></tr>
<tr class="separator:a922cb0b598034924c19e6695cc9f7513"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af3a794d5af0b3d72789293531468050a"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">testUnhandledCxxExceptionsAbortTheProgram</a> (self)</td></tr>
<tr class="separator:af3a794d5af0b3d72789293531468050a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7d02a890df0e3990aa107288c21f7dc7"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">testCatchesCxxExceptionsInFixtureConstructor</a> (self)</td></tr>
<tr class="separator:a7d02a890df0e3990aa107288c21f7dc7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3fe17da71b72c1693fa358f71c6b31be"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">testCatchesCxxExceptionsInFixtureDestructor</a> (self)</td></tr>
<tr class="separator:a3fe17da71b72c1693fa358f71c6b31be"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8e791760b553d92490005deea0812f44"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">testCatchesCxxExceptionsInSetUpTestCase</a> (self)</td></tr>
<tr class="separator:a8e791760b553d92490005deea0812f44"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a56c906c34e689ee016ab1bf14fe5220c"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">testCatchesCxxExceptionsInTearDownTestCase</a> (self)</td></tr>
<tr class="separator:a56c906c34e689ee016ab1bf14fe5220c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6451307941e063bcc3927992c1f2df54"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">testCatchesCxxExceptionsInSetUp</a> (self)</td></tr>
<tr class="separator:a6451307941e063bcc3927992c1f2df54"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a40ba50bf018753b7b21ed93ed60e4e1c"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">testCatchesCxxExceptionsInTearDown</a> (self)</td></tr>
<tr class="separator:a40ba50bf018753b7b21ed93ed60e4e1c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac73b336590a3d1c242124e9ea5464a42"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">testCatchesCxxExceptionsInTestBody</a> (self)</td></tr>
<tr class="separator:ac73b336590a3d1c242124e9ea5464a42"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a922cb0b598034924c19e6695cc9f7513"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">testCatchesNonStdCxxExceptions</a> (self)</td></tr>
<tr class="separator:a922cb0b598034924c19e6695cc9f7513"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af3a794d5af0b3d72789293531468050a"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">testUnhandledCxxExceptionsAbortTheProgram</a> (self)</td></tr>
<tr class="separator:af3a794d5af0b3d72789293531468050a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7d02a890df0e3990aa107288c21f7dc7"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">testCatchesCxxExceptionsInFixtureConstructor</a> (self)</td></tr>
<tr class="separator:a7d02a890df0e3990aa107288c21f7dc7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3fe17da71b72c1693fa358f71c6b31be"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">testCatchesCxxExceptionsInFixtureDestructor</a> (self)</td></tr>
<tr class="separator:a3fe17da71b72c1693fa358f71c6b31be"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8e791760b553d92490005deea0812f44"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">testCatchesCxxExceptionsInSetUpTestCase</a> (self)</td></tr>
<tr class="separator:a8e791760b553d92490005deea0812f44"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a56c906c34e689ee016ab1bf14fe5220c"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">testCatchesCxxExceptionsInTearDownTestCase</a> (self)</td></tr>
<tr class="separator:a56c906c34e689ee016ab1bf14fe5220c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6451307941e063bcc3927992c1f2df54"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">testCatchesCxxExceptionsInSetUp</a> (self)</td></tr>
<tr class="separator:a6451307941e063bcc3927992c1f2df54"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a40ba50bf018753b7b21ed93ed60e4e1c"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">testCatchesCxxExceptionsInTearDown</a> (self)</td></tr>
<tr class="separator:a40ba50bf018753b7b21ed93ed60e4e1c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac73b336590a3d1c242124e9ea5464a42"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">testCatchesCxxExceptionsInTestBody</a> (self)</td></tr>
<tr class="separator:ac73b336590a3d1c242124e9ea5464a42"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a922cb0b598034924c19e6695cc9f7513"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">testCatchesNonStdCxxExceptions</a> (self)</td></tr>
<tr class="separator:a922cb0b598034924c19e6695cc9f7513"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af3a794d5af0b3d72789293531468050a"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">testUnhandledCxxExceptionsAbortTheProgram</a> (self)</td></tr>
<tr class="separator:af3a794d5af0b3d72789293531468050a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><pre class="fragment">Tests C++ exception-catching behavior.

   Tests in this test case verify that:
   * C++ exceptions are caught and logged as C++ (not SEH) exceptions
   * Exception thrown affect the remainder of the test work flow in the
     expected manner.
</pre> 
<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00114">114</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
</div><h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a7d02a890df0e3990aa107288c21f7dc7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00123">123</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>Referenced by <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00123">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor()</a>.</p>
<div class="fragment"><div class="line"><a name="l00123"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">  123</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">testCatchesCxxExceptionsInFixtureConstructor</a>(self):</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;                 <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;                 <span class="stringliteral">&#39;in the test fixture\&#39;s constructor&#39;</span></div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInConstructorTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a7d02a890df0e3990aa107288c21f7dc7"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor</a></div><div class="ttdeci">def testCatchesCxxExceptionsInFixtureConstructor(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00123">gtest_catch_exceptions_test.py:123</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a7d02a890df0e3990aa107288c21f7dc7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00123">123</a> of file <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00123">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor()</a>.</p>
<div class="fragment"><div class="line"><a name="l00123"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">  123</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">testCatchesCxxExceptionsInFixtureConstructor</a>(self):</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;                 <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;                 <span class="stringliteral">&#39;in the test fixture\&#39;s constructor&#39;</span></div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInConstructorTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a7d02a890df0e3990aa107288c21f7dc7"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor</a></div><div class="ttdeci">def testCatchesCxxExceptionsInFixtureConstructor(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00123">gtest_catch_exceptions_test.py:123</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a7d02a890df0e3990aa107288c21f7dc7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00123">123</a> of file <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00123">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor()</a>.</p>
<div class="fragment"><div class="line"><a name="l00123"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">  123</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">testCatchesCxxExceptionsInFixtureConstructor</a>(self):</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;                 <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;                 <span class="stringliteral">&#39;in the test fixture\&#39;s constructor&#39;</span></div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInConstructorTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a7d02a890df0e3990aa107288c21f7dc7"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a7d02a890df0e3990aa107288c21f7dc7">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor</a></div><div class="ttdeci">def testCatchesCxxExceptionsInFixtureConstructor(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00123">gtest_catch_exceptions_test.py:123</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a3fe17da71b72c1693fa358f71c6b31be"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00136">136</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>Referenced by <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00136">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor()</a>.</p>
<div class="fragment"><div class="line"><a name="l00136"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">  136</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">testCatchesCxxExceptionsInFixtureDestructor</a>(self):</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;      self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;                   <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;                   <span class="stringliteral">&#39;in the test fixture\&#39;s destructor&#39;</span></div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;                   <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;      self.assert_(<span class="stringliteral">&#39;CxxExceptionInDestructorTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;                   <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;                   <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a3fe17da71b72c1693fa358f71c6b31be"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor</a></div><div class="ttdeci">def testCatchesCxxExceptionsInFixtureDestructor(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00136">gtest_catch_exceptions_test.py:136</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a3fe17da71b72c1693fa358f71c6b31be"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00136">136</a> of file <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00136">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor()</a>.</p>
<div class="fragment"><div class="line"><a name="l00136"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">  136</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">testCatchesCxxExceptionsInFixtureDestructor</a>(self):</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;      self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;                   <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;                   <span class="stringliteral">&#39;in the test fixture\&#39;s destructor&#39;</span></div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;                   <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;      self.assert_(<span class="stringliteral">&#39;CxxExceptionInDestructorTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;                   <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;                   <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a3fe17da71b72c1693fa358f71c6b31be"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor</a></div><div class="ttdeci">def testCatchesCxxExceptionsInFixtureDestructor(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00136">gtest_catch_exceptions_test.py:136</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a3fe17da71b72c1693fa358f71c6b31be"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00136">136</a> of file <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00136">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor()</a>.</p>
<div class="fragment"><div class="line"><a name="l00136"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">  136</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">testCatchesCxxExceptionsInFixtureDestructor</a>(self):</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;      self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;                   <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;                   <span class="stringliteral">&#39;in the test fixture\&#39;s destructor&#39;</span></div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;                   <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;      self.assert_(<span class="stringliteral">&#39;CxxExceptionInDestructorTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;                   <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;                   <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a3fe17da71b72c1693fa358f71c6b31be"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a3fe17da71b72c1693fa358f71c6b31be">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor</a></div><div class="ttdeci">def testCatchesCxxExceptionsInFixtureDestructor(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00136">gtest_catch_exceptions_test.py:136</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a6451307941e063bcc3927992c1f2df54"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00173">173</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>Referenced by <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00173">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp()</a>.</p>
<div class="fragment"><div class="line"><a name="l00173"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">  173</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">testCatchesCxxExceptionsInSetUp</a>(self):</div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;                 <span class="stringliteral">&#39; thrown in SetUp()&#39;</span></div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest destructor &#39;</span></div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDown() &#39;</span></div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInSetUpTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a6451307941e063bcc3927992c1f2df54"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp</a></div><div class="ttdeci">def testCatchesCxxExceptionsInSetUp(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00173">gtest_catch_exceptions_test.py:173</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a6451307941e063bcc3927992c1f2df54"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00173">173</a> of file <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00173">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp()</a>.</p>
<div class="fragment"><div class="line"><a name="l00173"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">  173</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">testCatchesCxxExceptionsInSetUp</a>(self):</div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;                 <span class="stringliteral">&#39; thrown in SetUp()&#39;</span></div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest destructor &#39;</span></div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDown() &#39;</span></div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInSetUpTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a6451307941e063bcc3927992c1f2df54"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp</a></div><div class="ttdeci">def testCatchesCxxExceptionsInSetUp(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00173">gtest_catch_exceptions_test.py:173</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a6451307941e063bcc3927992c1f2df54"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00173">173</a> of file <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00173">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp()</a>.</p>
<div class="fragment"><div class="line"><a name="l00173"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">  173</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">testCatchesCxxExceptionsInSetUp</a>(self):</div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;                 <span class="stringliteral">&#39; thrown in SetUp()&#39;</span></div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest destructor &#39;</span></div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDown() &#39;</span></div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInSetUpTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a6451307941e063bcc3927992c1f2df54"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a6451307941e063bcc3927992c1f2df54">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp</a></div><div class="ttdeci">def testCatchesCxxExceptionsInSetUp(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00173">gtest_catch_exceptions_test.py:173</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a8e791760b553d92490005deea0812f44"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00145">145</a> of file <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00145">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase()</a>.</p>
<div class="fragment"><div class="line"><a name="l00145"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">  145</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">testCatchesCxxExceptionsInSetUpTestCase</a>(self):</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;                 <span class="stringliteral">&#39; thrown in SetUpTestCase()&#39;</span></div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInConstructorTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest constructor &#39;</span></div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest destructor &#39;</span></div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::SetUp() &#39;</span></div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::TearDown() &#39;</span></div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest test body &#39;</span></div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a8e791760b553d92490005deea0812f44"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase</a></div><div class="ttdeci">def testCatchesCxxExceptionsInSetUpTestCase(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00145">gtest_catch_exceptions_test.py:145</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a8e791760b553d92490005deea0812f44"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00145">145</a> of file <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00145">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase()</a>.</p>
<div class="fragment"><div class="line"><a name="l00145"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">  145</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">testCatchesCxxExceptionsInSetUpTestCase</a>(self):</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;                 <span class="stringliteral">&#39; thrown in SetUpTestCase()&#39;</span></div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInConstructorTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest constructor &#39;</span></div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest destructor &#39;</span></div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::SetUp() &#39;</span></div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::TearDown() &#39;</span></div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest test body &#39;</span></div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a8e791760b553d92490005deea0812f44"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase</a></div><div class="ttdeci">def testCatchesCxxExceptionsInSetUpTestCase(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00145">gtest_catch_exceptions_test.py:145</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a8e791760b553d92490005deea0812f44"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00145">145</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>Referenced by <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00145">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase()</a>.</p>
<div class="fragment"><div class="line"><a name="l00145"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">  145</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">testCatchesCxxExceptionsInSetUpTestCase</a>(self):</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;                 <span class="stringliteral">&#39; thrown in SetUpTestCase()&#39;</span></div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInConstructorTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest constructor &#39;</span></div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest destructor &#39;</span></div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::SetUp() &#39;</span></div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::TearDown() &#39;</span></div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest test body &#39;</span></div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a8e791760b553d92490005deea0812f44"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a8e791760b553d92490005deea0812f44">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase</a></div><div class="ttdeci">def testCatchesCxxExceptionsInSetUpTestCase(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00145">gtest_catch_exceptions_test.py:145</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a40ba50bf018753b7b21ed93ed60e4e1c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00191">191</a> of file <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00191">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown()</a>.</p>
<div class="fragment"><div class="line"><a name="l00191"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">  191</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">testCatchesCxxExceptionsInTearDown</a>(self):</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;                 <span class="stringliteral">&#39; thrown in TearDown()&#39;</span></div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest destructor &#39;</span></div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a40ba50bf018753b7b21ed93ed60e4e1c"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTearDown(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00191">gtest_catch_exceptions_test.py:191</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a40ba50bf018753b7b21ed93ed60e4e1c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00191">191</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>Referenced by <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00191">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown()</a>.</p>
<div class="fragment"><div class="line"><a name="l00191"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">  191</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">testCatchesCxxExceptionsInTearDown</a>(self):</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;                 <span class="stringliteral">&#39; thrown in TearDown()&#39;</span></div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest destructor &#39;</span></div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a40ba50bf018753b7b21ed93ed60e4e1c"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTearDown(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00191">gtest_catch_exceptions_test.py:191</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a40ba50bf018753b7b21ed93ed60e4e1c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00191">191</a> of file <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00191">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown()</a>.</p>
<div class="fragment"><div class="line"><a name="l00191"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">  191</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">testCatchesCxxExceptionsInTearDown</a>(self):</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;                 <span class="stringliteral">&#39; thrown in TearDown()&#39;</span></div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest destructor &#39;</span></div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a40ba50bf018753b7b21ed93ed60e4e1c"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a40ba50bf018753b7b21ed93ed60e4e1c">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTearDown(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00191">gtest_catch_exceptions_test.py:191</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a56c906c34e689ee016ab1bf14fe5220c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00168">168</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>Referenced by <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00168">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase()</a>.</p>
<div class="fragment"><div class="line"><a name="l00168"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">  168</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">testCatchesCxxExceptionsInTearDownTestCase</a>(self):</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;                 <span class="stringliteral">&#39; thrown in TearDownTestCase()&#39;</span></div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a56c906c34e689ee016ab1bf14fe5220c"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTearDownTestCase(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00168">gtest_catch_exceptions_test.py:168</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a56c906c34e689ee016ab1bf14fe5220c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00168">168</a> of file <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00168">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase()</a>.</p>
<div class="fragment"><div class="line"><a name="l00168"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">  168</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">testCatchesCxxExceptionsInTearDownTestCase</a>(self):</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;                 <span class="stringliteral">&#39; thrown in TearDownTestCase()&#39;</span></div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a56c906c34e689ee016ab1bf14fe5220c"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTearDownTestCase(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00168">gtest_catch_exceptions_test.py:168</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a56c906c34e689ee016ab1bf14fe5220c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00168">168</a> of file <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00168">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase()</a>.</p>
<div class="fragment"><div class="line"><a name="l00168"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">  168</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">testCatchesCxxExceptionsInTearDownTestCase</a>(self):</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;                 <span class="stringliteral">&#39; thrown in TearDownTestCase()&#39;</span></div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a56c906c34e689ee016ab1bf14fe5220c"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a56c906c34e689ee016ab1bf14fe5220c">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTearDownTestCase(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00168">gtest_catch_exceptions_test.py:168</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="ac73b336590a3d1c242124e9ea5464a42"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00202">202</a> of file <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00202">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody()</a>.</p>
<div class="fragment"><div class="line"><a name="l00202"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">  202</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">testCatchesCxxExceptionsInTestBody</a>(self):</div><div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;                 <span class="stringliteral">&#39; thrown in the test body&#39;</span></div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest destructor &#39;</span></div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDown() &#39;</span></div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_ac73b336590a3d1c242124e9ea5464a42"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTestBody(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00202">gtest_catch_exceptions_test.py:202</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="ac73b336590a3d1c242124e9ea5464a42"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00202">202</a> of file <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00202">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody()</a>.</p>
<div class="fragment"><div class="line"><a name="l00202"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">  202</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">testCatchesCxxExceptionsInTestBody</a>(self):</div><div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;                 <span class="stringliteral">&#39; thrown in the test body&#39;</span></div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest destructor &#39;</span></div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDown() &#39;</span></div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_ac73b336590a3d1c242124e9ea5464a42"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTestBody(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00202">gtest_catch_exceptions_test.py:202</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="ac73b336590a3d1c242124e9ea5464a42"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00202">202</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>Referenced by <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00202">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody()</a>.</p>
<div class="fragment"><div class="line"><a name="l00202"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">  202</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">testCatchesCxxExceptionsInTestBody</a>(self):</div><div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;                 <span class="stringliteral">&#39; thrown in the test body&#39;</span></div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest destructor &#39;</span></div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDown() &#39;</span></div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_ac73b336590a3d1c242124e9ea5464a42"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ac73b336590a3d1c242124e9ea5464a42">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTestBody(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00202">gtest_catch_exceptions_test.py:202</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a922cb0b598034924c19e6695cc9f7513"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00216">216</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>Referenced by <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00216">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions()</a>.</p>
<div class="fragment"><div class="line"><a name="l00216"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">  216</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">testCatchesNonStdCxxExceptions</a>(self):</div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    self.assert_(<span class="stringliteral">&#39;Unknown C++ exception thrown in the test body&#39;</span></div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a922cb0b598034924c19e6695cc9f7513"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions</a></div><div class="ttdeci">def testCatchesNonStdCxxExceptions(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00216">gtest_catch_exceptions_test.py:216</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a922cb0b598034924c19e6695cc9f7513"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00216">216</a> of file <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00216">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions()</a>.</p>
<div class="fragment"><div class="line"><a name="l00216"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">  216</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">testCatchesNonStdCxxExceptions</a>(self):</div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    self.assert_(<span class="stringliteral">&#39;Unknown C++ exception thrown in the test body&#39;</span></div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a922cb0b598034924c19e6695cc9f7513"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions</a></div><div class="ttdeci">def testCatchesNonStdCxxExceptions(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00216">gtest_catch_exceptions_test.py:216</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a922cb0b598034924c19e6695cc9f7513"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00216">216</a> of file <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00216">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions()</a>.</p>
<div class="fragment"><div class="line"><a name="l00216"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">  216</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">testCatchesNonStdCxxExceptions</a>(self):</div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    self.assert_(<span class="stringliteral">&#39;Unknown C++ exception thrown in the test body&#39;</span></div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_a922cb0b598034924c19e6695cc9f7513"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a922cb0b598034924c19e6695cc9f7513">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions</a></div><div class="ttdeci">def testCatchesNonStdCxxExceptions(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00216">gtest_catch_exceptions_test.py:216</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="af3a794d5af0b3d72789293531468050a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00220">220</a> of file <a class="el" href="wangle_2__build_2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__test__utils_8py_source.html#l00306">gtest_test_utils.Main()</a>, and <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00220">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram()</a>.</p>
<div class="fragment"><div class="line"><a name="l00220"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">  220</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">testUnhandledCxxExceptionsAbortTheProgram</a>(self):</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    <span class="comment"># Filters out SEH exception tests on Windows. Unhandled SEH exceptions</span></div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    <span class="comment"># cause tests to show pop-up windows there.</span></div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + <span class="stringliteral">&#39;=-*Seh*&#39;</span></div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    <span class="comment"># By default, Google Test doesn&#39;t catch the exceptions.</span></div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;    uncaught_exceptions_ex_binary_output = <a class="code" href="classgtest__test__utils_1_1Subprocess.html">gtest_test_utils.Subprocess</a>(</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;        [EX_EXE_PATH,</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;         NO_CATCH_EXCEPTIONS_FLAG,</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;         FITLER_OUT_SEH_TESTS_FLAG],</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;        env=environ).output</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;</div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;    self.assert_(<span class="stringliteral">&#39;Unhandled C++ exception terminating the program&#39;</span></div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;                 <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_af3a794d5af0b3d72789293531468050a"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram</a></div><div class="ttdeci">def testUnhandledCxxExceptionsAbortTheProgram(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00220">gtest_catch_exceptions_test.py:220</a></div></div>
<div class="ttc" id="classgtest__test__utils_1_1Subprocess_html"><div class="ttname"><a href="classgtest__test__utils_1_1Subprocess.html">gtest_test_utils.Subprocess</a></div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__test__utils_8py_source.html#l00207">gtest_test_utils.py:207</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="af3a794d5af0b3d72789293531468050a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00220">220</a> of file <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__test__utils_8py_source.html#l00306">gtest_test_utils.Main()</a>.</p>

<p>Referenced by <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00220">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram()</a>.</p>
<div class="fragment"><div class="line"><a name="l00220"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">  220</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">testUnhandledCxxExceptionsAbortTheProgram</a>(self):</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    <span class="comment"># Filters out SEH exception tests on Windows. Unhandled SEH exceptions</span></div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    <span class="comment"># cause tests to show pop-up windows there.</span></div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + <span class="stringliteral">&#39;=-*Seh*&#39;</span></div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    <span class="comment"># By default, Google Test doesn&#39;t catch the exceptions.</span></div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;    uncaught_exceptions_ex_binary_output = <a class="code" href="classgtest__test__utils_1_1Subprocess.html">gtest_test_utils.Subprocess</a>(</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;        [EX_EXE_PATH,</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;         NO_CATCH_EXCEPTIONS_FLAG,</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;         FITLER_OUT_SEH_TESTS_FLAG],</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;        env=environ).output</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;</div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;    self.assert_(<span class="stringliteral">&#39;Unhandled C++ exception terminating the program&#39;</span></div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;                 <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_af3a794d5af0b3d72789293531468050a"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram</a></div><div class="ttdeci">def testUnhandledCxxExceptionsAbortTheProgram(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00220">gtest_catch_exceptions_test.py:220</a></div></div>
<div class="ttc" id="classgtest__test__utils_1_1Subprocess_html"><div class="ttname"><a href="classgtest__test__utils_1_1Subprocess.html">gtest_test_utils.Subprocess</a></div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__test__utils_8py_source.html#l00207">gtest_test_utils.py:207</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="af3a794d5af0b3d72789293531468050a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00220">220</a> of file <a class="el" href="lib_2test_2googletest-release-1_88_80_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>

<p>References <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__test__utils_8py_source.html#l00306">gtest_test_utils.Main()</a>, and <a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00220">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram()</a>.</p>
<div class="fragment"><div class="line"><a name="l00220"></a><span class="lineno"><a class="line" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">  220</a></span>&#160;  <span class="keyword">def </span><a class="code" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">testUnhandledCxxExceptionsAbortTheProgram</a>(self):</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    <span class="comment"># Filters out SEH exception tests on Windows. Unhandled SEH exceptions</span></div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    <span class="comment"># cause tests to show pop-up windows there.</span></div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + <span class="stringliteral">&#39;=-*Seh*&#39;</span></div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    <span class="comment"># By default, Google Test doesn&#39;t catch the exceptions.</span></div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;    uncaught_exceptions_ex_binary_output = <a class="code" href="classgtest__test__utils_1_1Subprocess.html">gtest_test_utils.Subprocess</a>(</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;        [EX_EXE_PATH,</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;         NO_CATCH_EXCEPTIONS_FLAG,</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;         FITLER_OUT_SEH_TESTS_FLAG],</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;        env=environ).output</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;</div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;    self.assert_(<span class="stringliteral">&#39;Unhandled C++ exception terminating the program&#39;</span></div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;                 <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;</div><div class="ttc" id="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_html_af3a794d5af0b3d72789293531468050a"><div class="ttname"><a href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#af3a794d5af0b3d72789293531468050a">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram</a></div><div class="ttdeci">def testUnhandledCxxExceptionsAbortTheProgram(self)</div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html#l00220">gtest_catch_exceptions_test.py:220</a></div></div>
<div class="ttc" id="classgtest__test__utils_1_1Subprocess_html"><div class="ttname"><a href="classgtest__test__utils_1_1Subprocess.html">gtest_test_utils.Subprocess</a></div><div class="ttdef"><b>Definition:</b> <a href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__test__utils_8py_source.html#l00207">gtest_test_utils.py:207</a></div></div>
</div><!-- fragment -->
</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>proxygen/fizz/build_/gtest/src/gtest/googletest/test/<a class="el" href="fizz_2build___2gtest_2src_2gtest_2googletest_2test_2gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="namespacegtest__catch__exceptions__test.html">gtest_catch_exceptions_test</a></li><li class="navelem"><a class="el" href="classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html">CatchCxxExceptionsTest</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
